// Minimal sparse syscall table for the Windows Nyx pipeline.
// The indices must match the IDs in prog.GetTarget("windows", "amd64").

#include <winternl.h>

// Declare NT APIs not in mingw headers (exported by ntdll.dll, linked via -lntdll)
extern "C" {
NTSTATUS NTAPI NtCreateFile(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, PIO_STATUS_BLOCK, PLARGE_INTEGER, ULONG, ULONG, ULONG, ULONG, PVOID, ULONG);
NTSTATUS NTAPI NtReadFile(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, PVOID, ULONG, PLARGE_INTEGER, PULONG);
NTSTATUS NTAPI NtWriteFile(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, PVOID, ULONG, PLARGE_INTEGER, PULONG);
NTSTATUS NTAPI NtFsControlFile(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, ULONG, PVOID, ULONG, PVOID, ULONG);
NTSTATUS NTAPI NtDeviceIoControlFile(HANDLE, HANDLE, PIO_APC_ROUTINE, PVOID, PIO_STATUS_BLOCK, ULONG, PVOID, ULONG, PVOID, ULONG);
NTSTATUS NTAPI NtCancelIoFileEx(HANDLE, PIO_STATUS_BLOCK, PIO_STATUS_BLOCK);
NTSTATUS NTAPI NtQueryInformationFile(HANDLE, PIO_STATUS_BLOCK, PVOID, ULONG, FILE_INFORMATION_CLASS);
NTSTATUS NTAPI NtSetInformationFile(HANDLE, PIO_STATUS_BLOCK, PVOID, ULONG, FILE_INFORMATION_CLASS);
NTSTATUS NTAPI NtDelayExecution(BOOLEAN, PLARGE_INTEGER);
NTSTATUS NTAPI NtYieldExecution();
NTSTATUS NTAPI NtQueryTimerResolution(PULONG, PULONG, PULONG);
NTSTATUS NTAPI NtSetTimerResolution(ULONG, BOOLEAN, PULONG);
NTSTATUS NTAPI NtQuerySystemTime(PLARGE_INTEGER);
NTSTATUS NTAPI NtQueryPerformanceCounter(PLARGE_INTEGER, PLARGE_INTEGER);
NTSTATUS NTAPI NtPowerInformation(POWER_INFORMATION_LEVEL, PVOID, ULONG, PVOID, ULONG);
NTSTATUS NTAPI NtFlushInstructionCache(HANDLE, PVOID, ULONG);
NTSTATUS NTAPI NtFlushWriteBuffer();
NTSTATUS NTAPI NtQueryDefaultLocale(BOOLEAN, PLCID);
NTSTATUS NTAPI NtQueryDefaultUILanguage(LANGID*);
}

// Windows syscall IDs — from prog.GetTarget("windows","amd64").SyscallMap
// Generated: go run ./tools/idxcheck/main.go
#define W32_CANCELIOEX_AFD_ACCEPT_SUPER_DISCONNECT_PENDING 135
#define W32_CANCELIOEX_AFD_ACCEPT_SUPER_DISCONNECT_PENDING_NONBLOCK 136
#define W32_CANCELIOEX_AFD_ADDRESS_LIST_CHANGE_PENDING 137
#define W32_CANCELIOEX_AFD_ADDRESS_LIST_CHANGE_PENDING_NONBLOCK 138
#define W32_CANCELIOEX_AFD_LISTEN_IRP_PENDING 139
#define W32_CANCELIOEX_AFD_LISTEN_IRP_PENDING_LIFO 140
#define W32_CANCELIOEX_AFD_LISTEN_IRP_PENDING_LIFO_NONBLOCK 141
#define W32_CANCELIOEX_AFD_LISTEN_IRP_PENDING_NONBLOCK 142
#define W32_CANCELIOEX_AFD_ROUTING_INTERFACE_CHANGE_PENDING 143
#define W32_CANCELIOEX_AFD_ROUTING_INTERFACE_CHANGE_PENDING_NONBLOCK 144
#define W32_CANCELIOEX_AFD_SAN_CONTEXT   145
#define W32_CANCELIOEX_AFD_SUPER_DISCONNECT_PENDING 146
#define W32_CANCELIOEX_AFD_SUPER_DISCONNECT_PENDING_NONBLOCK 147
#define W32_CANCELIOEX_AFD_TLI_PENDING   148
#define W32_CANCELIOEX_AFD_UDP_PEER_SEND_MESSAGE_PENDING 149
#define W32_CANCELIOEX_AFD_UDP_SEND_DATAGRAM_PENDING 150
#define W32_CANCELIOEX_AFD_UDP_SEND_MESSAGE_PENDING 151
#define W32_CANCELIOEX_AFD_UDP_SEND_PENDING 152
#define W32_CANCELIO_AFD_ADDRESS_LIST_CHANGE_PENDING 121
#define W32_CANCELIO_AFD_ADDRESS_LIST_CHANGE_PENDING_NONBLOCK 122
#define W32_CANCELIO_AFD_LISTEN_IRP_PENDING 123
#define W32_CANCELIO_AFD_LISTEN_IRP_PENDING_LIFO 124
#define W32_CANCELIO_AFD_LISTEN_IRP_PENDING_LIFO_NONBLOCK 125
#define W32_CANCELIO_AFD_LISTEN_IRP_PENDING_NONBLOCK 126
#define W32_CANCELIO_AFD_ROUTING_INTERFACE_CHANGE_PENDING 127
#define W32_CANCELIO_AFD_ROUTING_INTERFACE_CHANGE_PENDING_NONBLOCK 128
#define W32_CANCELIO_AFD_TLI_PENDING     129
#define W32_CANCELIO_AFD_UDP_PEER_SEND_MESSAGE_PENDING 130
#define W32_CANCELIO_AFD_UDP_SEND_DATAGRAM_PENDING 131
#define W32_CANCELIO_AFD_UDP_SEND_MESSAGE_PENDING 132
#define W32_CANCELIO_AFD_UDP_SEND_PENDING 133
#define W32_CLOSEHANDLE                  325
#define W32_CLOSEHANDLE_AFD_ACCEPT_SUPER_DISCONNECT_PENDING 326
#define W32_CLOSEHANDLE_AFD_ACCEPT_SUPER_DISCONNECT_PENDING_NONBLOCK 327
#define W32_CLOSEHANDLE_AFD_ACCEPT_TRANSMIT_CLOSING 328
#define W32_CLOSEHANDLE_AFD_ACCEPT_TRANSMIT_CLOSING_NONBLOCK 329
#define W32_CLOSEHANDLE_AFD_ACCEPT_TRANSMIT_PENDING 330
#define W32_CLOSEHANDLE_AFD_ACCEPT_TRANSMIT_PENDING_NONBLOCK 331
#define W32_CLOSEHANDLE_AFD_ADDRESS_LIST_CHANGE_PENDING 332
#define W32_CLOSEHANDLE_AFD_ADDRESS_LIST_CHANGE_PENDING_NONBLOCK 333
#define W32_CLOSEHANDLE_AFD_LISTEN_IRP_PENDING 334
#define W32_CLOSEHANDLE_AFD_LISTEN_IRP_PENDING_LIFO 335
#define W32_CLOSEHANDLE_AFD_LISTEN_IRP_PENDING_LIFO_NONBLOCK 336
#define W32_CLOSEHANDLE_AFD_LISTEN_IRP_PENDING_NONBLOCK 337
#define W32_CLOSEHANDLE_AFD_RIO_ENDPOINT 338
#define W32_CLOSEHANDLE_AFD_RIO_REGISTRATION_DOMAIN 339
#define W32_CLOSEHANDLE_AFD_RIO_RQPAIR   340
#define W32_CLOSEHANDLE_AFD_ROUTING_INTERFACE_CHANGE_PENDING 341
#define W32_CLOSEHANDLE_AFD_ROUTING_INTERFACE_CHANGE_PENDING_NONBLOCK 342
#define W32_CLOSEHANDLE_AFD_SAN_CONTEXT  343
#define W32_CLOSEHANDLE_AFD_SAN_ENDPOINT 344
#define W32_CLOSEHANDLE_AFD_SAN_HELPER   345
#define W32_CLOSEHANDLE_AFD_SUPER_DISCONNECT_PENDING 346
#define W32_CLOSEHANDLE_AFD_SUPER_DISCONNECT_PENDING_NONBLOCK 347
#define W32_CLOSEHANDLE_AFD_TCP_ACCEPTED 348
#define W32_CLOSEHANDLE_AFD_TCP_ACCEPTED_NONBLOCK 349
#define W32_CLOSEHANDLE_AFD_TCP_BOUND    350
#define W32_CLOSEHANDLE_AFD_TCP_BOUND_NONBLOCK 351
#define W32_CLOSEHANDLE_AFD_TCP_CONNECTED 352
#define W32_CLOSEHANDLE_AFD_TCP_CONNECTED_NONBLOCK 353
#define W32_CLOSEHANDLE_AFD_TCP_CREATED  354
#define W32_CLOSEHANDLE_AFD_TCP_CREATED_NONBLOCK 355
#define W32_CLOSEHANDLE_AFD_TCP_DISCONNECTED 356
#define W32_CLOSEHANDLE_AFD_TCP_LISTENING 359
#define W32_CLOSEHANDLE_AFD_TCP_LISTENING_DELAYED 360
#define W32_CLOSEHANDLE_AFD_TCP_LISTENING_DELAYED_NONBLOCK 361
#define W32_CLOSEHANDLE_AFD_TCP_LISTENING_NONBLOCK 362
#define W32_CLOSEHANDLE_AFD_TCP_LISTEN_BACKLOG 357
#define W32_CLOSEHANDLE_AFD_TCP_LISTEN_BACKLOG_NONBLOCK 358
#define W32_CLOSEHANDLE_AFD_TCP_SEND_CONNECT_DATA 363
#define W32_CLOSEHANDLE_AFD_TCP_SEND_CONNECT_OPTIONS 364
#define W32_CLOSEHANDLE_AFD_TCP_SEND_DISCONNECT_DATA 365
#define W32_CLOSEHANDLE_AFD_TCP_SEND_DISCONNECT_OPTIONS 366
#define W32_CLOSEHANDLE_AFD_TCP_TRANSMIT_CLOSING 367
#define W32_CLOSEHANDLE_AFD_TCP_TRANSMIT_CLOSING_NONBLOCK 368
#define W32_CLOSEHANDLE_AFD_TCP_TRANSMIT_PENDING 369
#define W32_CLOSEHANDLE_AFD_TCP_TRANSMIT_PENDING_NONBLOCK 370
#define W32_CLOSEHANDLE_AFD_TLI_ENDPOINT 371
#define W32_CLOSEHANDLE_AFD_TLI_PENDING  372
#define W32_CLOSEHANDLE_AFD_UDP_BOUND    373
#define W32_CLOSEHANDLE_AFD_UDP_BOUND_NONBLOCK 374
#define W32_CLOSEHANDLE_AFD_UDP_CREATED  375
#define W32_CLOSEHANDLE_AFD_UDP_CREATED_NONBLOCK 376
#define W32_CLOSEHANDLE_AFD_UDP_PEERED   378
#define W32_CLOSEHANDLE_AFD_UDP_PEERED_EXTERNAL 379
#define W32_CLOSEHANDLE_AFD_UDP_PEERED_EXTERNAL_NONBLOCK 380
#define W32_CLOSEHANDLE_AFD_UDP_PEERED_NONBLOCK 381
#define W32_CLOSEHANDLE_AFD_UDP_PEER_SEND_MESSAGE_PENDING 377
#define W32_CLOSEHANDLE_AFD_UDP_SEND_CONNECT_DATA 382
#define W32_CLOSEHANDLE_AFD_UDP_SEND_CONNECT_OPTIONS 383
#define W32_CLOSEHANDLE_AFD_UDP_SEND_DATAGRAM_PENDING 384
#define W32_CLOSEHANDLE_AFD_UDP_SEND_DISCONNECT_DATA 385
#define W32_CLOSEHANDLE_AFD_UDP_SEND_DISCONNECT_OPTIONS 386
#define W32_CLOSEHANDLE_AFD_UDP_SEND_MESSAGE_PENDING 387
#define W32_CLOSEHANDLE_AFD_UDP_SEND_PENDING 388
#define W32_CREATEEVENTA                 472
#define W32_CREATEEVENTA_AUTO            473
#define W32_CREATEEVENTA_MANUAL          474
#define W32_CREATEFILE2                  478
#define W32_CREATEFILEA                  479
#define W32_CREATEFILEA_AFD_TRANSMIT     480
#define W32_CREATEIOCOMPLETIONPORT       500
#define W32_CREATEIOCOMPLETIONPORT_CREATE 502
#define W32_DELETEFILEA                  743
#define W32_FLUSHFILEBUFFERS             988
#define W32_GETCURRENTPROCESS_PROCESS    1125
#define W32_GETCURRENTTHREAD_THREAD      1130
#define W32_GETKERNELOBJECTSECURITY_AFD_ENDPOINT 1232
#define W32_NTCANCELIOFILEEX_AFD_ACCEPT_SUPER_DISCONNECT_PENDING 1905
#define W32_NTCANCELIOFILEEX_AFD_ACCEPT_SUPER_DISCONNECT_PENDING_NONBLOCK 1906
#define W32_NTCANCELIOFILEEX_AFD_ACCEPT_TRANSMIT_PENDING 1907
#define W32_NTCANCELIOFILEEX_AFD_ACCEPT_TRANSMIT_PENDING_NONBLOCK 1908
#define W32_NTCANCELIOFILEEX_AFD_ADDRESS_LIST_CHANGE_PENDING 1909
#define W32_NTCANCELIOFILEEX_AFD_ADDRESS_LIST_CHANGE_PENDING_NONBLOCK 1910
#define W32_NTCANCELIOFILEEX_AFD_LISTEN_IRP_PENDING 1911
#define W32_NTCANCELIOFILEEX_AFD_LISTEN_IRP_PENDING_LIFO 1912
#define W32_NTCANCELIOFILEEX_AFD_LISTEN_IRP_PENDING_LIFO_NONBLOCK 1913
#define W32_NTCANCELIOFILEEX_AFD_LISTEN_IRP_PENDING_NONBLOCK 1914
#define W32_NTCANCELIOFILEEX_AFD_ROUTING_INTERFACE_CHANGE_PENDING 1915
#define W32_NTCANCELIOFILEEX_AFD_ROUTING_INTERFACE_CHANGE_PENDING_NONBLOCK 1916
#define W32_NTCANCELIOFILEEX_AFD_SAN_CONTEXT 1917
#define W32_NTCANCELIOFILEEX_AFD_SUPER_DISCONNECT_PENDING 1918
#define W32_NTCANCELIOFILEEX_AFD_SUPER_DISCONNECT_PENDING_NONBLOCK 1919
#define W32_NTCANCELIOFILEEX_AFD_TCP_CONNECT_PENDING 1920
#define W32_NTCANCELIOFILEEX_AFD_TCP_CONNECT_PENDING_NONBLOCK 1921
#define W32_NTCANCELIOFILEEX_AFD_TCP_TRANSMIT_PENDING 1922
#define W32_NTCANCELIOFILEEX_AFD_TCP_TRANSMIT_PENDING_NONBLOCK 1923
#define W32_NTCANCELIOFILEEX_AFD_TLI_PENDING 1924
#define W32_NTCANCELIOFILEEX_AFD_UDP_PEER_SEND_MESSAGE_PENDING 1925
#define W32_NTCANCELIOFILEEX_AFD_UDP_SEND_DATAGRAM_PENDING 1926
#define W32_NTCANCELIOFILEEX_AFD_UDP_SEND_MESSAGE_PENDING 1927
#define W32_NTCANCELIOFILEEX_AFD_UDP_SEND_PENDING 1928
#define W32_NTCREATEFILE_AFD_RIO_REGISTRATION_DOMAIN 1929
#define W32_NTCREATEFILE_AFD_RIO_TCP_ENDPOINT 1930
#define W32_NTCREATEFILE_AFD_SAN_HELPER  1931
#define W32_NTCREATEFILE_AFD_TCP_ACCEPT_SLOT 1932
#define W32_NTCREATEFILE_AFD_TCP_ENDPOINT 1933
#define W32_NTCREATEFILE_AFD_TLI_TCP_ENDPOINT 1934
#define W32_NTCREATEFILE_AFD_UDP_ENDPOINT 1935
#define W32_NTDELAYEXEC                  1936
#define W32_NTDEVICEIOCTLFILE            1937
#define W32_NTDEVICEIOCTLFILE_AFD_ACCEPT_TCP 1938
#define W32_NTDEVICEIOCTLFILE_AFD_ACCEPT_TCP_NONBLOCK 1939
#define W32_NTDEVICEIOCTLFILE_AFD_ADDRESS_LIST_CHANGE_UDP 1940
#define W32_NTDEVICEIOCTLFILE_AFD_ADDRESS_LIST_CHANGE_UDP_NONBLOCK 1941
#define W32_NTDEVICEIOCTLFILE_AFD_ADDR_LIST_QUERY_UDP 1942
#define W32_NTDEVICEIOCTLFILE_AFD_BIND_TCP 1943
#define W32_NTDEVICEIOCTLFILE_AFD_BIND_TCP_LISTENER 1944
#define W32_NTDEVICEIOCTLFILE_AFD_BIND_TCP_LISTENER_NONBLOCK 1945
#define W32_NTDEVICEIOCTLFILE_AFD_BIND_TCP_NONBLOCK 1946
#define W32_NTDEVICEIOCTLFILE_AFD_BIND_UDP 1947
#define W32_NTDEVICEIOCTLFILE_AFD_BIND_UDP_NONBLOCK 1948
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECTEX_TCP 1961
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECTEX_TCP_NONBLOCK 1962
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECTEX_UDP 1963
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECTEX_UDP_NONBLOCK 1964
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP 1949
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_CLIENT_TO_LISTENER 1950
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_CLIENT_TO_LISTENER_NONBLOCK 1951
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_NONBLOCK 1952
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_TO_DELAYED_LISTENER 1953
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_TO_DELAYED_LISTENER_NONBLOCK 1954
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_TO_LISTENER 1955
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_TO_LISTENER_NONBLOCK 1956
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_UDP 1957
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_UDP_LOOPBACK 1958
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_UDP_LOOPBACK_NONBLOCK 1959
#define W32_NTDEVICEIOCTLFILE_AFD_CONNECT_UDP_NONBLOCK 1960
#define W32_NTDEVICEIOCTLFILE_AFD_DEFER_ACCEPT_REJECT_TCP 1965
#define W32_NTDEVICEIOCTLFILE_AFD_DEFER_ACCEPT_REJECT_TCP_NONBLOCK 1966
#define W32_NTDEVICEIOCTLFILE_AFD_DEFER_ACCEPT_REQUEUE_TCP 1967
#define W32_NTDEVICEIOCTLFILE_AFD_DEFER_ACCEPT_REQUEUE_TCP_NONBLOCK 1968
#define W32_NTDEVICEIOCTLFILE_AFD_ENUM_NETWORK_EVENTS_ACCEPT 1969
#define W32_NTDEVICEIOCTLFILE_AFD_ENUM_NETWORK_EVENTS_ACCEPT_NONBLOCK 1970
#define W32_NTDEVICEIOCTLFILE_AFD_EVENT_SELECT_ACCEPT 1971
#define W32_NTDEVICEIOCTLFILE_AFD_EVENT_SELECT_ACCEPT_NONBLOCK 1972
#define W32_NTDEVICEIOCTLFILE_AFD_GET_ADDRESS_TCP 1973
#define W32_NTDEVICEIOCTLFILE_AFD_GET_ADDRESS_UDP 1974
#define W32_NTDEVICEIOCTLFILE_AFD_GET_CONTEXT_TCP 1975
#define W32_NTDEVICEIOCTLFILE_AFD_GET_CONTEXT_UDP 1976
#define W32_NTDEVICEIOCTLFILE_AFD_GET_INFORMATION_TCP 1977
#define W32_NTDEVICEIOCTLFILE_AFD_GET_INFORMATION_UDP 1978
#define W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_ACCEPT 1979
#define W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_TCP 1980
#define W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_TCP_SET 1981
#define W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_TLI 1982
#define W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_UDP 1983
#define W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_UDP_SET 1984
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_CONNECT_DATA_TCP 1985
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_CONNECT_DATA_UDP 1986
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_CONNECT_OPTIONS_TCP 1987
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_CONNECT_OPTIONS_UDP 1988
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_DISCONNECT_DATA_TCP 1989
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_DISCONNECT_DATA_UDP 1990
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_DISCONNECT_OPTIONS_TCP 1991
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_DISCONNECT_OPTIONS_UDP 1992
#define W32_NTDEVICEIOCTLFILE_AFD_GET_REMOTE_ADDRESS_TCP 1993
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RETURNED_RECEIVE_CONNECT_DATA_LENGTH_TCP 1994
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RETURNED_RECEIVE_CONNECT_OPTIONS_LENGTH_TCP 1995
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RETURNED_RECEIVE_DISCONNECT_DATA_LENGTH_TCP 1996
#define W32_NTDEVICEIOCTLFILE_AFD_GET_RETURNED_RECEIVE_DISCONNECT_OPTIONS_LENGTH_TCP 1997
#define W32_NTDEVICEIOCTLFILE_AFD_GET_UNACCEPTED_CONNECT_DATA_TCP 1998
#define W32_NTDEVICEIOCTLFILE_AFD_NOOP_ACCEPT 1999
#define W32_NTDEVICEIOCTLFILE_AFD_NOOP_ACCEPT_PENDING 2000
#define W32_NTDEVICEIOCTLFILE_AFD_NOOP_ACCEPT_PENDING_NONBLOCK 2001
#define W32_NTDEVICEIOCTLFILE_AFD_NOOP_PREACCEPTED 2002
#define W32_NTDEVICEIOCTLFILE_AFD_NOOP_PREACCEPTED_NONBLOCK 2003
#define W32_NTDEVICEIOCTLFILE_AFD_NOOP_TCP 2004
#define W32_NTDEVICEIOCTLFILE_AFD_NOOP_TCP_DISCONNECTED 2005
#define W32_NTDEVICEIOCTLFILE_AFD_NOOP_TCP_LISTENING_NONBLOCK 2006
#define W32_NTDEVICEIOCTLFILE_AFD_NOOP_UDP 2007
#define W32_NTDEVICEIOCTLFILE_AFD_NOTIFY_SOCK_DRAIN 2008
#define W32_NTDEVICEIOCTLFILE_AFD_NOTIFY_SOCK_REGISTER 2009
#define W32_NTDEVICEIOCTLFILE_AFD_PARTIAL_DISCONNECT_TCP 2010
#define W32_NTDEVICEIOCTLFILE_AFD_POLL_ACCEPT 2011
#define W32_NTDEVICEIOCTLFILE_AFD_POLL_ACCEPT_NONBLOCK 2012
#define W32_NTDEVICEIOCTLFILE_AFD_QUERY_HANDLES_ACCEPT 2013
#define W32_NTDEVICEIOCTLFILE_AFD_QUERY_HANDLES_TCP 2014
#define W32_NTDEVICEIOCTLFILE_AFD_QUERY_HANDLES_UDP 2015
#define W32_NTDEVICEIOCTLFILE_AFD_QUERY_HANDLES_UDP_PEER 2016
#define W32_NTDEVICEIOCTLFILE_AFD_QUERY_RECV_ACCEPT 2017
#define W32_NTDEVICEIOCTLFILE_AFD_QUERY_RECV_TCP 2018
#define W32_NTDEVICEIOCTLFILE_AFD_QUERY_RECV_TCP_IRP 2019
#define W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_ACCEPT_NONBLOCK 2020
#define W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_DATAGRAM_UDP_BOUND_NONBLOCK 2021
#define W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_DATAGRAM_UDP_BOUND_NONBLOCK_FAST 2022
#define W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_DATAGRAM_UDP_PEER_NONBLOCK 2023
#define W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_DATAGRAM_UDP_PEER_NONBLOCK_FAST 2024
#define W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_MESSAGE_UDP_BOUND_NONBLOCK 2025
#define W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_MESSAGE_UDP_PEER_NONBLOCK 2026
#define W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_TCP_NONBLOCK 2027
#define W32_NTDEVICEIOCTLFILE_AFD_RIO_CREATE_CQ 2028
#define W32_NTDEVICEIOCTLFILE_AFD_RIO_CREATE_RQPAIR 2029
#define W32_NTDEVICEIOCTLFILE_AFD_RIO_DEREGISTER_BUFFER 2030
#define W32_NTDEVICEIOCTLFILE_AFD_RIO_DESTROY_CQ 2031
#define W32_NTDEVICEIOCTLFILE_AFD_RIO_FLUSH_RECEIVE 2032
#define W32_NTDEVICEIOCTLFILE_AFD_RIO_FLUSH_SEND 2033
#define W32_NTDEVICEIOCTLFILE_AFD_RIO_NOTIFY_CQ 2034
#define W32_NTDEVICEIOCTLFILE_AFD_RIO_REGISTER_BUFFER 2035
#define W32_NTDEVICEIOCTLFILE_AFD_RIO_RESIZE_CQ 2036
#define W32_NTDEVICEIOCTLFILE_AFD_RIO_RESIZE_RQPAIR 2037
#define W32_NTDEVICEIOCTLFILE_AFD_ROUTING_INTERFACE_CHANGE_UDP 2038
#define W32_NTDEVICEIOCTLFILE_AFD_ROUTING_INTERFACE_CHANGE_UDP_NONBLOCK 2039
#define W32_NTDEVICEIOCTLFILE_AFD_ROUTING_INTERFACE_QUERY_UDP 2040
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_ACQUIRE_CONTEXT 2041
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_ADDR_LIST_CHANGE 2042
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_CONNECT_HANDLER 2043
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_CEMENT_ENDPOINT 2044
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_COMPLETE_ACCEPT 2045
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_COMPLETE_IO 2046
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_COMPLETE_REQUEST 2047
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_GET_PHYSICAL_ADDR 2048
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_GET_SERVICE_PID 2049
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_PROVIDER_CHANGE 2050
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_REFRESH_ENDPOINT 2051
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_RESET_EVENTS 2052
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_SET_EVENTS 2053
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_SET_SERVICE_PROCESS 2054
#define W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_TRANSFER_CTX 2055
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_ACCEPT 2056
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_ACCEPT_NONBLOCK 2057
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_DATAGRAM_UDP_BOUND 2058
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_DATAGRAM_UDP_BOUND_NONBLOCK 2059
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_DATAGRAM_UDP_BOUND_NONBLOCK_IRP 2060
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_DATAGRAM_UDP_BOUND_NONBLOCK_SOCKADDR 2061
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_DATAGRAM_UDP_BOUND_SOCKADDR 2062
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_ACCEPT 2063
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_ACCEPT_NONBLOCK 2064
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_TCP 2065
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_TCP_NONBLOCK 2066
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_UDP_BOUND 2067
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_UDP_BOUND_NONBLOCK 2068
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_UDP_PEER 2069
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_UDP_PEER_NONBLOCK 2070
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_TCP 2071
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_TCP_NONBLOCK 2072
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_UDP_PEER 2073
#define W32_NTDEVICEIOCTLFILE_AFD_SEND_UDP_PEER_NONBLOCK 2074
#define W32_NTDEVICEIOCTLFILE_AFD_SET_CONTEXT_TCP 2075
#define W32_NTDEVICEIOCTLFILE_AFD_SET_CONTEXT_UDP 2076
#define W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_TCP_ACCEPTED 2077
#define W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_TCP_BOUND 2078
#define W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_TCP_CONNECTED 2079
#define W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_TCP_CREATED 2080
#define W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_TCP_LISTENING 2081
#define W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_UDP_BOUND 2082
#define W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_UDP_CREATED 2083
#define W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_UDP_PEERED 2084
#define W32_NTDEVICEIOCTLFILE_AFD_SET_QOS_TCP 2085
#define W32_NTDEVICEIOCTLFILE_AFD_SET_QOS_TLI 2086
#define W32_NTDEVICEIOCTLFILE_AFD_SET_QOS_UDP 2087
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_CONNECT_DATA_LENGTH_TCP 2088
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_CONNECT_DATA_LENGTH_UDP 2089
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_CONNECT_OPTIONS_LENGTH_TCP 2090
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_CONNECT_OPTIONS_LENGTH_UDP 2091
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_DISCONNECT_DATA_LENGTH_TCP 2092
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_DISCONNECT_DATA_LENGTH_UDP 2093
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_DISCONNECT_OPTIONS_LENGTH_TCP 2094
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_DISCONNECT_OPTIONS_LENGTH_UDP 2095
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RETURNED_RECEIVE_CONNECT_DATA_LENGTH_TCP 2096
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RETURNED_RECEIVE_CONNECT_OPTIONS_LENGTH_TCP 2097
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RETURNED_RECEIVE_DISCONNECT_DATA_LENGTH_TCP 2098
#define W32_NTDEVICEIOCTLFILE_AFD_SET_RETURNED_RECEIVE_DISCONNECT_OPTIONS_LENGTH_TCP 2099
#define W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_CONNECT_DATA_TCP 2100
#define W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_CONNECT_DATA_UDP 2101
#define W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_CONNECT_OPTIONS_TCP 2102
#define W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_CONNECT_OPTIONS_UDP 2103
#define W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_DISCONNECT_DATA_TCP 2104
#define W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_DISCONNECT_DATA_UDP 2105
#define W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_DISCONNECT_OPTIONS_TCP 2106
#define W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_DISCONNECT_OPTIONS_UDP 2107
#define W32_NTDEVICEIOCTLFILE_AFD_SOCKET_TRANSFER_BEGIN 2108
#define W32_NTDEVICEIOCTLFILE_AFD_SOCKET_TRANSFER_END 2109
#define W32_NTDEVICEIOCTLFILE_AFD_SQM    2110
#define W32_NTDEVICEIOCTLFILE_AFD_START_LISTEN_TCP 2111
#define W32_NTDEVICEIOCTLFILE_AFD_START_LISTEN_TCP_DELAYED 2112
#define W32_NTDEVICEIOCTLFILE_AFD_START_LISTEN_TCP_DELAYED_NONBLOCK 2113
#define W32_NTDEVICEIOCTLFILE_AFD_START_LISTEN_TCP_NONBLOCK 2114
#define W32_NTDEVICEIOCTLFILE_AFD_SUPER_ACCEPT_TCP 2115
#define W32_NTDEVICEIOCTLFILE_AFD_SUPER_ACCEPT_TCP_NONBLOCK 2116
#define W32_NTDEVICEIOCTLFILE_AFD_SUPER_CONNECT_TCP 2117
#define W32_NTDEVICEIOCTLFILE_AFD_SUPER_CONNECT_TCP_NONBLOCK 2118
#define W32_NTDEVICEIOCTLFILE_AFD_SUPER_CONNECT_TLI 2119
#define W32_NTDEVICEIOCTLFILE_AFD_SUPER_DISCONNECT_ACCEPT 2120
#define W32_NTDEVICEIOCTLFILE_AFD_SUPER_DISCONNECT_ACCEPT_NONBLOCK 2121
#define W32_NTDEVICEIOCTLFILE_AFD_SUPER_DISCONNECT_TCP 2122
#define W32_NTDEVICEIOCTLFILE_AFD_SUPER_DISCONNECT_TCP_NONBLOCK 2123
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_ASSOCIATE_QOS 2124
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_ISB_QUERY 2125
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_ISB_SET 2126
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_SET_QOS 2127
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE1_INBUF 2128
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE1_NOBUF 2129
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE1_OUTBUF 2130
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE2_INBUF 2131
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE2_NOBUF 2132
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE2_OUTBUF 2133
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE3_INBUF 2134
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE3_NOBUF 2135
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE3_NOBUF_PENDING 2136
#define W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE3_OUTBUF 2137
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_ACCEPT 2138
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_ACCEPT_NONBLOCK 2139
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_BUFFERS_ACCEPT_NONBLOCK 2140
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_BUFFERS_TCP_NONBLOCK 2141
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_DISCONNECT_ACCEPT 2142
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_DISCONNECT_ACCEPT_NONBLOCK 2143
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_DISCONNECT_TCP 2144
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_DISCONNECT_TCP_NONBLOCK 2145
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_REUSE_ACCEPT 2146
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_REUSE_ACCEPT_NONBLOCK 2147
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_REUSE_TCP 2148
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_REUSE_TCP_NONBLOCK 2149
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_TCP 2150
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_TCP_NONBLOCK 2151
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_ACCEPT 2152
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_ACCEPT_NONBLOCK 2153
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_DISCONNECT_ACCEPT 2154
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_DISCONNECT_ACCEPT_NONBLOCK 2155
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_DISCONNECT_TCP 2156
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_DISCONNECT_TCP_NONBLOCK 2157
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_FILE_ACCEPT_NONBLOCK 2158
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_FILE_TCP_NONBLOCK 2159
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_REUSE_ACCEPT 2160
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_REUSE_ACCEPT_NONBLOCK 2161
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_REUSE_TCP 2162
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_REUSE_TCP_NONBLOCK 2163
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_TCP 2164
#define W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_TCP_NONBLOCK 2165
#define W32_NTDEVICEIOCTLFILE_AFD_UNBIND_TCP 2166
#define W32_NTDEVICEIOCTLFILE_AFD_UNBIND_UDP 2167
#define W32_NTDEVICEIOCTLFILE_AFD_UNCONNECT_UDP 2168
#define W32_NTDEVICEIOCTLFILE_AFD_VALIDATE_GROUP_RECHECK_TCP 2169
#define W32_NTDEVICEIOCTLFILE_AFD_VALIDATE_GROUP_RECHECK_UDP 2170
#define W32_NTDEVICEIOCTLFILE_AFD_VALIDATE_GROUP_TCP 2171
#define W32_NTDEVICEIOCTLFILE_AFD_VALIDATE_GROUP_UDP 2172
#define W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_DELAYED_TCP 2173
#define W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_DELAYED_TCP_NONBLOCK 2174
#define W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_LIFO_PENDING_TCP 2175
#define W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_LIFO_PENDING_TCP_NONBLOCK 2176
#define W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_LIFO_TCP 2177
#define W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_LIFO_TCP_NONBLOCK 2178
#define W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_PENDING_TCP 2179
#define W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_PENDING_TCP_NONBLOCK 2180
#define W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_TCP 2181
#define W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_TCP_NONBLOCK 2182
#define W32_NTFLUSHICACHE                2183
#define W32_NTFLUSHWBUF                  2184
#define W32_NTFSCONTROLFILE              2185
#define W32_NTFSCONTROLFILE_NTFS_GET_COMP 2186
#define W32_NTFSCONTROLFILE_NTFS_QUERY_ALLOC_RANGES 2187
#define W32_NTFSCONTROLFILE_NTFS_SET_COMP 2188
#define W32_NTFSCONTROLFILE_NTFS_SET_SPARSE 2189
#define W32_NTFSCONTROLFILE_NTFS_SET_ZERO_DATA 2190
#define W32_NTPOWERINFO                  2191
#define W32_NTQINFOFILE_BASIC            2194
#define W32_NTQINFOFILE_NETOPEN          2195
#define W32_NTQINFOFILE_STANDARD         2196
#define W32_NTQINFO_PROC                 2197
#define W32_NTQINFO_SYS                  2199
#define W32_NTQUERYDEFLOCALE             2192
#define W32_NTQUERYDEFUILANG             2193
#define W32_NTQUERYPERFCTR               2198
#define W32_NTQUERYSYSTIME               2200
#define W32_NTQUERYTIMERRES              2201
#define W32_NTREADFILE                   2202
#define W32_NTREADFILE_AFD_ACCEPT_NONBLOCK 2203
#define W32_NTREADFILE_AFD_TCP_NONBLOCK  2204
#define W32_NTREADFILE_AFD_UDP_PEER_NONBLOCK 2205
#define W32_NTSETINFOFILE_BASIC          2206
#define W32_NTSETINFO_PROC               2207
#define W32_NTSETTIMERRES                2208
#define W32_NTWRITEFILE                  2209
#define W32_NTWRITEFILE_AFD_ACCEPT       2210
#define W32_NTWRITEFILE_AFD_ACCEPT_NONBLOCK 2211
#define W32_NTWRITEFILE_AFD_TCP          2212
#define W32_NTWRITEFILE_AFD_TCP_NONBLOCK 2213
#define W32_NTWRITEFILE_AFD_UDP_PEER     2214
#define W32_NTWRITEFILE_AFD_UDP_PEER_NONBLOCK 2215
#define W32_NTYIELDEXEC                  2216
#define W32_READFILE                     2367
#define W32_SETFILEINFOBYHANDLE          2757
#define W32_SETKERNELOBJECTSECURITY_AFD_ENDPOINT 2781
#define W32_SYZ_EMIT_ETHERNET_WINDOWS    3342
#define W32_SYZ_EXTRACT_TCP_RES_WINDOWS  3344
#define W32_SYZ_EXTRACT_TCP_RES_WINDOWS_SYNACK 3345
#define W32_SYZ_KAFL_BUGCHECK_TRIGGER    3346
#define W32_VIRTUALALLOC                 3083
#define W32_WRITEFILE                    3189
#define W32_WRITEFILE_AFD_TRANSMIT       3190
#define W32_WSACLEANUP                   3128
#define W32_WSASTARTUP                   3140
#include "windows_service_26200.h"

static call_t syscalls[4096];

static syscall_t make_nyx_ntos_service_stub(uint32 service_number)
{
	const SIZE_T stub_size = 11;
	auto* code = reinterpret_cast<unsigned char*>(
	    VirtualAlloc(nullptr, stub_size, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE));
	if (!code)
		failmsg("ntos service stub allocation failed", "service=%u", service_number);
	code[0] = 0x4c;
	code[1] = 0x8b;
	code[2] = 0xd1;
	code[3] = 0xb8;
	memcpy(code + 4, &service_number, sizeof(service_number));
	code[8] = 0x0f;
	code[9] = 0x05;
	code[10] = 0xc3;
	return reinterpret_cast<syscall_t>(code);
}

static void init_nyx_ntos_service(int target_id, const char* target_name, const char* service_name,
				  uint32 service_number)
{
	(void)service_name;
	syscalls[target_id] =
	    call_t{target_name, static_cast<int>(service_number), {}, make_nyx_ntos_service_stub(service_number)};
}

static void init_nyx_syscalls()
{
	static bool initialized;
	if (initialized)
		return;
	initialized = true;
	syscalls[W32_VIRTUALALLOC] = call_t{"VirtualAlloc", 0, {}, (syscall_t)VirtualAlloc};
	syscalls[W32_GETCURRENTPROCESS_PROCESS] = call_t{"GetCurrentProcess$process", 0, {}, (syscall_t)GetCurrentProcess};
	syscalls[W32_GETCURRENTTHREAD_THREAD] = call_t{"GetCurrentThread$thread", 0, {}, (syscall_t)GetCurrentThread};
	syscalls[W32_NTQINFOFILE_BASIC] = call_t{"NtQueryInformationFile$basic", 0, {}, (syscall_t)NtQueryInformationFile};
	syscalls[W32_NTQINFOFILE_NETOPEN] = call_t{"NtQueryInformationFile$network_open", 0, {}, (syscall_t)NtQueryInformationFile};
	syscalls[W32_NTQINFOFILE_STANDARD] = call_t{"NtQueryInformationFile$standard", 0, {}, (syscall_t)NtQueryInformationFile};
	syscalls[W32_NTQINFO_PROC] = call_t{"NtQueryInformationProcess", 0, {}, (syscall_t)NtQueryInformationProcess};
	syscalls[W32_NTQINFO_SYS] = call_t{"NtQuerySystemInformation", 0, {}, (syscall_t)NtQuerySystemInformation};
	syscalls[W32_NTSETINFO_PROC] = call_t{"NtSetInformationProcess", 0, {}, (syscall_t)NtSetInformationProcess};
	syscalls[W32_CLOSEHANDLE] = call_t{"CloseHandle", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TLI_PENDING] = call_t{"CloseHandle$afd_tli_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CREATEEVENTA] = call_t{"CreateEventA", 0, {}, (syscall_t)CreateEventA};
	syscalls[W32_CREATEEVENTA_AUTO] = call_t{"CreateEventA$auto", 0, {
									     0,
									     0,
									     0,
									     0,
									     0,
									     0,
									     0,
									     0,
									     0,
									     0,
									     1,
									 },
						 (syscall_t)CreateEventA};
	syscalls[W32_CREATEEVENTA_MANUAL] = call_t{"CreateEventA$manual", 0, {
										 0,
										 0,
										 0,
										 0,
										 0,
										 0,
										 0,
										 0,
										 0,
										 0,
										 1,
									     },
						   (syscall_t)CreateEventA};
	syscalls[W32_CREATEIOCOMPLETIONPORT] = call_t{"CreateIoCompletionPort", 0, {}, (syscall_t)CreateIoCompletionPort};
	syscalls[W32_CREATEIOCOMPLETIONPORT_CREATE] = call_t{"CreateIoCompletionPort$create", 0, {}, (syscall_t)CreateIoCompletionPort};
	syscalls[W32_CREATEFILEA] = call_t{"CreateFileA", 0, {}, (syscall_t)CreateFileA};
	syscalls[W32_CREATEFILEA_AFD_TRANSMIT] = call_t{"CreateFileA$afd_transmit", 0, {}, (syscall_t)CreateFileA};
	syscalls[W32_CREATEFILE2] = call_t{"CreateFile2", 0, {}, (syscall_t)CreateFile2};
	syscalls[W32_DELETEFILEA] = call_t{"DeleteFileA", 0, {}, (syscall_t)DeleteFileA};
	syscalls[W32_FLUSHFILEBUFFERS] = call_t{"FlushFileBuffers", 0, {}, (syscall_t)FlushFileBuffers};
	syscalls[W32_CANCELIO_AFD_TLI_PENDING] = call_t{"CancelIo$afd_tli_pending", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIOEX_AFD_TLI_PENDING] = call_t{"CancelIoEx$afd_tli_pending", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_READFILE] = call_t{"ReadFile", 0, {}, (syscall_t)ReadFile};
	syscalls[W32_SETFILEINFOBYHANDLE] = call_t{"SetFileInformationByHandle", 0, {}, (syscall_t)SetFileInformationByHandle};
	syscalls[W32_WRITEFILE] = call_t{"WriteFile", 0, {}, (syscall_t)WriteFile};
	syscalls[W32_WRITEFILE_AFD_TRANSMIT] = call_t{"WriteFile$afd_transmit", 0, {}, (syscall_t)WriteFile};
	syscalls[W32_WSACLEANUP] = call_t{"WSACleanup", 0, {}, (syscall_t)WSACleanup};
	syscalls[W32_WSASTARTUP] = call_t{"WSAStartup", 0, {}, (syscall_t)WSAStartup};
	syscalls[W32_SYZ_EMIT_ETHERNET_WINDOWS] = call_t{"syz_emit_ethernet$windows", 0, {
											     0,
											     0,
											     0,
											     0,
											     0,
											     1,
											     1,
											 },
							 (syscall_t)syz_emit_ethernet};
	syscalls[W32_SYZ_EXTRACT_TCP_RES_WINDOWS] = call_t{"syz_extract_tcp_res$windows", 0, {
												 0,
												 0,
												 0,
												 0,
												 0,
												 1,
												 1,
											     },
							   (syscall_t)syz_extract_tcp_res};
	syscalls[W32_SYZ_EXTRACT_TCP_RES_WINDOWS_SYNACK] = call_t{"syz_extract_tcp_res$windows_synack", 0, {
													       0,
													       0,
													       0,
													       0,
													       0,
													       1,
													       1,
													   },
								  (syscall_t)syz_extract_tcp_res};
	syscalls[W32_SYZ_KAFL_BUGCHECK_TRIGGER] = call_t{"syz_kafl_bugcheck_trigger", 0, {
											     0,
											     0,
											     0,
											     0,
											     0,
											     1,
											     1,
											 },
							 (syscall_t)syz_kafl_bugcheck_trigger};
	// New no-context NT syscalls
	syscalls[W32_NTDELAYEXEC] = call_t{"NtDelayExecution", 0, {}, (syscall_t)NtDelayExecution};
	syscalls[W32_NTYIELDEXEC] = call_t{"NtYieldExecution", 0, {}, (syscall_t)NtYieldExecution};
	syscalls[W32_NTQUERYTIMERRES] = call_t{"NtQueryTimerResolution", 0, {}, (syscall_t)NtQueryTimerResolution};
	syscalls[W32_NTSETTIMERRES] = call_t{"NtSetTimerResolution", 0, {}, (syscall_t)NtSetTimerResolution};
	syscalls[W32_NTQUERYSYSTIME] = call_t{"NtQuerySystemTime", 0, {}, (syscall_t)NtQuerySystemTime};
	syscalls[W32_NTQUERYPERFCTR] = call_t{"NtQueryPerformanceCounter", 0, {}, (syscall_t)NtQueryPerformanceCounter};
	syscalls[W32_NTPOWERINFO] = call_t{"NtPowerInformation", 0, {}, (syscall_t)NtPowerInformation};
	syscalls[W32_NTFLUSHICACHE] = call_t{"NtFlushInstructionCache", 0, {}, (syscall_t)NtFlushInstructionCache};
	syscalls[W32_NTFLUSHWBUF] = call_t{"NtFlushWriteBuffer", 0, {}, (syscall_t)NtFlushWriteBuffer};
	syscalls[W32_NTQUERYDEFLOCALE] = call_t{"NtQueryDefaultLocale", 0, {}, (syscall_t)NtQueryDefaultLocale};
	syscalls[W32_NTQUERYDEFUILANG] = call_t{"NtQueryDefaultUILanguage", 0, {}, (syscall_t)NtQueryDefaultUILanguage};
	syscalls[W32_NTCANCELIOFILEEX_AFD_ACCEPT_SUPER_DISCONNECT_PENDING] = call_t{"NtCancelIoFileEx$afd_accept_super_disconnect_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_ACCEPT_SUPER_DISCONNECT_PENDING_NONBLOCK] = call_t{"NtCancelIoFileEx$afd_accept_super_disconnect_pending_nonblock", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_ACCEPT_TRANSMIT_PENDING] = call_t{"NtCancelIoFileEx$afd_accept_transmit_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_ACCEPT_TRANSMIT_PENDING_NONBLOCK] = call_t{"NtCancelIoFileEx$afd_accept_transmit_pending_nonblock", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_ADDRESS_LIST_CHANGE_PENDING] = call_t{"NtCancelIoFileEx$afd_address_list_change_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_ADDRESS_LIST_CHANGE_PENDING_NONBLOCK] = call_t{"NtCancelIoFileEx$afd_address_list_change_pending_nonblock", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_LISTEN_IRP_PENDING] = call_t{"NtCancelIoFileEx$afd_listen_irp_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_LISTEN_IRP_PENDING_LIFO] = call_t{"NtCancelIoFileEx$afd_listen_irp_pending_lifo", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_LISTEN_IRP_PENDING_LIFO_NONBLOCK] = call_t{"NtCancelIoFileEx$afd_listen_irp_pending_lifo_nonblock", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_LISTEN_IRP_PENDING_NONBLOCK] = call_t{"NtCancelIoFileEx$afd_listen_irp_pending_nonblock", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_ROUTING_INTERFACE_CHANGE_PENDING] = call_t{"NtCancelIoFileEx$afd_routing_interface_change_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_ROUTING_INTERFACE_CHANGE_PENDING_NONBLOCK] = call_t{"NtCancelIoFileEx$afd_routing_interface_change_pending_nonblock", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_SAN_CONTEXT] = call_t{"NtCancelIoFileEx$afd_san_context", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_SUPER_DISCONNECT_PENDING] = call_t{"NtCancelIoFileEx$afd_super_disconnect_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_SUPER_DISCONNECT_PENDING_NONBLOCK] = call_t{"NtCancelIoFileEx$afd_super_disconnect_pending_nonblock", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_TCP_CONNECT_PENDING] = call_t{"NtCancelIoFileEx$afd_tcp_connect_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_TCP_CONNECT_PENDING_NONBLOCK] = call_t{"NtCancelIoFileEx$afd_tcp_connect_pending_nonblock", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_TCP_TRANSMIT_PENDING] = call_t{"NtCancelIoFileEx$afd_tcp_transmit_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_TCP_TRANSMIT_PENDING_NONBLOCK] = call_t{"NtCancelIoFileEx$afd_tcp_transmit_pending_nonblock", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_TLI_PENDING] = call_t{"NtCancelIoFileEx$afd_tli_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_UDP_PEER_SEND_MESSAGE_PENDING] = call_t{"NtCancelIoFileEx$afd_udp_peer_send_message_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_UDP_SEND_DATAGRAM_PENDING] = call_t{"NtCancelIoFileEx$afd_udp_send_datagram_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_UDP_SEND_MESSAGE_PENDING] = call_t{"NtCancelIoFileEx$afd_udp_send_message_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCANCELIOFILEEX_AFD_UDP_SEND_PENDING] = call_t{"NtCancelIoFileEx$afd_udp_send_pending", 0, {0, 0, 0, 0, 0, 1, 1, }, (syscall_t)NtCancelIoFileEx};
	syscalls[W32_NTCREATEFILE_AFD_RIO_REGISTRATION_DOMAIN] = call_t{"NtCreateFile$afd_rio_registration_domain", 0, {}, (syscall_t)NtCreateFile};
	syscalls[W32_NTCREATEFILE_AFD_RIO_TCP_ENDPOINT] = call_t{"NtCreateFile$afd_rio_tcp_endpoint", 0, {}, (syscall_t)NtCreateFile};
	syscalls[W32_NTCREATEFILE_AFD_TLI_TCP_ENDPOINT] = call_t{"NtCreateFile$afd_tli_tcp_endpoint", 0, {}, (syscall_t)NtCreateFile};
	syscalls[W32_NTCREATEFILE_AFD_TCP_ACCEPT_SLOT] = call_t{"NtCreateFile$afd_tcp_accept_slot", 0, {}, (syscall_t)NtCreateFile};
	syscalls[W32_NTCREATEFILE_AFD_TCP_ENDPOINT] = call_t{"NtCreateFile$afd_tcp_endpoint", 0, {}, (syscall_t)NtCreateFile};
	syscalls[W32_NTCREATEFILE_AFD_UDP_ENDPOINT] = call_t{"NtCreateFile$afd_udp_endpoint", 0, {}, (syscall_t)NtCreateFile};
	syscalls[W32_NTDEVICEIOCTLFILE] = call_t{"NtDeviceIoControlFile", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_ADDR_LIST_QUERY_UDP] = call_t{"NtDeviceIoControlFile$afd_address_list_query_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_ADDRESS_LIST_CHANGE_UDP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_address_list_change_udp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_ACCEPT_TCP] = call_t{"NtDeviceIoControlFile$afd_accept_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_input_handle8_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_ACCEPT_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_accept_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_input_handle8_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_BIND_TCP] = call_t{"NtDeviceIoControlFile$afd_bind_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_BIND_TCP_LISTENER] = call_t{"NtDeviceIoControlFile$afd_bind_tcp_listener", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_BIND_TCP_LISTENER_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_bind_tcp_listener_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_BIND_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_bind_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_BIND_UDP] = call_t{"NtDeviceIoControlFile$afd_bind_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_BIND_UDP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_bind_udp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP] = call_t{"NtDeviceIoControlFile$afd_connect_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_CLIENT_TO_LISTENER] = call_t{"NtDeviceIoControlFile$afd_connect_tcp_client_to_listener", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_CLIENT_TO_LISTENER_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_connect_tcp_client_to_listener_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_connect_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_TO_DELAYED_LISTENER] = call_t{"NtDeviceIoControlFile$afd_connect_tcp_to_delayed_listener", 0, {}, (syscall_t)windows_nt_device_io_control_file_input_handle16_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_TO_DELAYED_LISTENER_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_connect_tcp_to_delayed_listener_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_input_handle16_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_TO_LISTENER] = call_t{"NtDeviceIoControlFile$afd_connect_tcp_to_listener", 0, {}, (syscall_t)windows_nt_device_io_control_file_input_handle16_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_TCP_TO_LISTENER_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_connect_tcp_to_listener_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_input_handle16_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_UDP] = call_t{"NtDeviceIoControlFile$afd_connect_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_UDP_LOOPBACK] = call_t{"NtDeviceIoControlFile$afd_connect_udp_loopback", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_UDP_LOOPBACK_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_connect_udp_loopback_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECT_UDP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_connect_udp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_DEFER_ACCEPT_REJECT_TCP] = call_t{"NtDeviceIoControlFile$afd_defer_accept_reject_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_DEFER_ACCEPT_REJECT_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_defer_accept_reject_tcp_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_DEFER_ACCEPT_REQUEUE_TCP] = call_t{"NtDeviceIoControlFile$afd_defer_accept_requeue_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_DEFER_ACCEPT_REQUEUE_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_defer_accept_requeue_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_ENUM_NETWORK_EVENTS_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_enum_network_events_accept", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_ENUM_NETWORK_EVENTS_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_enum_network_events_accept_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_EVENT_SELECT_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_event_select_accept", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_EVENT_SELECT_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_event_select_accept_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_ADDRESS_TCP] = call_t{"NtDeviceIoControlFile$afd_get_address_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_ADDRESS_UDP] = call_t{"NtDeviceIoControlFile$afd_get_address_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_CONTEXT_TCP] = call_t{"NtDeviceIoControlFile$afd_get_context_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_CONTEXT_UDP] = call_t{"NtDeviceIoControlFile$afd_get_context_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_INFORMATION_TCP] = call_t{"NtDeviceIoControlFile$afd_get_information_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_INFORMATION_UDP] = call_t{"NtDeviceIoControlFile$afd_get_information_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_get_qos_accept", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_TCP] = call_t{"NtDeviceIoControlFile$afd_get_qos_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_UDP] = call_t{"NtDeviceIoControlFile$afd_get_qos_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_CONNECT_DATA_TCP] = call_t{"NtDeviceIoControlFile$afd_get_receive_connect_data_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_CONNECT_DATA_UDP] = call_t{"NtDeviceIoControlFile$afd_get_receive_connect_data_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_CONNECT_OPTIONS_TCP] = call_t{"NtDeviceIoControlFile$afd_get_receive_connect_options_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_CONNECT_OPTIONS_UDP] = call_t{"NtDeviceIoControlFile$afd_get_receive_connect_options_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_DISCONNECT_DATA_TCP] = call_t{"NtDeviceIoControlFile$afd_get_receive_disconnect_data_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_DISCONNECT_DATA_UDP] = call_t{"NtDeviceIoControlFile$afd_get_receive_disconnect_data_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_DISCONNECT_OPTIONS_TCP] = call_t{"NtDeviceIoControlFile$afd_get_receive_disconnect_options_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RECEIVE_DISCONNECT_OPTIONS_UDP] = call_t{"NtDeviceIoControlFile$afd_get_receive_disconnect_options_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_REMOTE_ADDRESS_TCP] = call_t{"NtDeviceIoControlFile$afd_get_remote_address_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RETURNED_RECEIVE_CONNECT_DATA_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_get_returned_receive_connect_data_length_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RETURNED_RECEIVE_CONNECT_OPTIONS_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_get_returned_receive_connect_options_length_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RETURNED_RECEIVE_DISCONNECT_DATA_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_get_returned_receive_disconnect_data_length_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_RETURNED_RECEIVE_DISCONNECT_OPTIONS_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_get_returned_receive_disconnect_options_length_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_UNACCEPTED_CONNECT_DATA_TCP] = call_t{"NtDeviceIoControlFile$afd_get_unaccepted_connect_data_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_NOOP_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_noop_accept", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_NOOP_ACCEPT_PENDING] = call_t{"NtDeviceIoControlFile$afd_noop_accept_pending", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_NOOP_ACCEPT_PENDING_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_noop_accept_pending_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_NOOP_PREACCEPTED] = call_t{"NtDeviceIoControlFile$afd_noop_preaccepted", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_NOOP_PREACCEPTED_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_noop_preaccepted_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_NOOP_TCP] = call_t{"NtDeviceIoControlFile$afd_noop_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_NOOP_TCP_DISCONNECTED] = call_t{"NtDeviceIoControlFile$afd_noop_tcp_disconnected", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_NOOP_TCP_LISTENING_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_noop_tcp_listening_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_NOOP_UDP] = call_t{"NtDeviceIoControlFile$afd_noop_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_PARTIAL_DISCONNECT_TCP] = call_t{"NtDeviceIoControlFile$afd_partial_disconnect_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_POLL_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_poll_accept", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_POLL_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_poll_accept_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_QUERY_HANDLES_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_query_handles_accept", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_QUERY_HANDLES_TCP] = call_t{"NtDeviceIoControlFile$afd_query_handles_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_QUERY_HANDLES_UDP] = call_t{"NtDeviceIoControlFile$afd_query_handles_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_QUERY_HANDLES_UDP_PEER] = call_t{"NtDeviceIoControlFile$afd_query_handles_udp_peer", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_QUERY_RECV_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_query_recv_accept", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_QUERY_RECV_TCP] = call_t{"NtDeviceIoControlFile$afd_query_recv_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_QUERY_RECV_TCP_IRP] = call_t{"NtDeviceIoControlFile$afd_query_recv_tcp_irp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_receive_accept_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_DATAGRAM_UDP_BOUND_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_receive_datagram_udp_bound_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_DATAGRAM_UDP_BOUND_NONBLOCK_FAST] = call_t{"NtDeviceIoControlFile$afd_receive_datagram_udp_bound_nonblock_fast", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_DATAGRAM_UDP_PEER_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_receive_datagram_udp_peer_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_DATAGRAM_UDP_PEER_NONBLOCK_FAST] = call_t{"NtDeviceIoControlFile$afd_receive_datagram_udp_peer_nonblock_fast", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_receive_tcp_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RIO_CREATE_CQ] = call_t{"NtDeviceIoControlFile$afd_rio_create_cq", 0, {}, (syscall_t)windows_nt_device_io_control_file_output_int32_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RIO_CREATE_RQPAIR] = call_t{"NtDeviceIoControlFile$afd_rio_create_rqpair", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RIO_DEREGISTER_BUFFER] = call_t{"NtDeviceIoControlFile$afd_rio_deregister_buffer", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RIO_DESTROY_CQ] = call_t{"NtDeviceIoControlFile$afd_rio_destroy_cq", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RIO_FLUSH_RECEIVE] = call_t{"NtDeviceIoControlFile$afd_rio_flush_receive", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RIO_FLUSH_SEND] = call_t{"NtDeviceIoControlFile$afd_rio_flush_send", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RIO_NOTIFY_CQ] = call_t{"NtDeviceIoControlFile$afd_rio_notify_cq", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RIO_REGISTER_BUFFER] = call_t{"NtDeviceIoControlFile$afd_rio_register_buffer", 0, {}, (syscall_t)windows_nt_device_io_control_file_output_int32_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RIO_RESIZE_CQ] = call_t{"NtDeviceIoControlFile$afd_rio_resize_cq", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RIO_RESIZE_RQPAIR] = call_t{"NtDeviceIoControlFile$afd_rio_resize_rqpair", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_ASSOCIATE_QOS] = call_t{"NtDeviceIoControlFile$afd_tli_associate_qos", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_ISB_QUERY] = call_t{"NtDeviceIoControlFile$afd_tli_isb_query", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_ISB_SET] = call_t{"NtDeviceIoControlFile$afd_tli_isb_set", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_SET_QOS] = call_t{"NtDeviceIoControlFile$afd_tli_set_qos", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE1_INBUF] = call_t{"NtDeviceIoControlFile$afd_tli_type1_inbuf", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE1_NOBUF] = call_t{"NtDeviceIoControlFile$afd_tli_type1_nobuf", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE1_OUTBUF] = call_t{"NtDeviceIoControlFile$afd_tli_type1_outbuf", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE2_INBUF] = call_t{"NtDeviceIoControlFile$afd_tli_type2_inbuf", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE2_NOBUF] = call_t{"NtDeviceIoControlFile$afd_tli_type2_nobuf", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE2_OUTBUF] = call_t{"NtDeviceIoControlFile$afd_tli_type2_outbuf", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE3_INBUF] = call_t{"NtDeviceIoControlFile$afd_tli_type3_inbuf", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE3_NOBUF] = call_t{"NtDeviceIoControlFile$afd_tli_type3_nobuf", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE3_NOBUF_PENDING] = call_t{"NtDeviceIoControlFile$afd_tli_type3_nobuf_pending", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TLI_TYPE3_OUTBUF] = call_t{"NtDeviceIoControlFile$afd_tli_type3_outbuf", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_ROUTING_INTERFACE_CHANGE_UDP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_routing_interface_change_udp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_ROUTING_INTERFACE_QUERY_UDP] = call_t{"NtDeviceIoControlFile$afd_routing_interface_query_udp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_send_accept", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_send_accept_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_DATAGRAM_UDP_BOUND] = call_t{"NtDeviceIoControlFile$afd_send_datagram_udp_bound", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_DATAGRAM_UDP_BOUND_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_send_datagram_udp_bound_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_DATAGRAM_UDP_BOUND_NONBLOCK_IRP] = call_t{"NtDeviceIoControlFile$afd_send_datagram_udp_bound_nonblock_irp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_DATAGRAM_UDP_BOUND_SOCKADDR] = call_t{"NtDeviceIoControlFile$afd_send_datagram_udp_bound_sockaddr", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_DATAGRAM_UDP_BOUND_NONBLOCK_SOCKADDR] = call_t{"NtDeviceIoControlFile$afd_send_datagram_udp_bound_nonblock_sockaddr", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_TCP] = call_t{"NtDeviceIoControlFile$afd_send_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_send_tcp_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_UDP_PEER] = call_t{"NtDeviceIoControlFile$afd_send_udp_peer", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_UDP_PEER_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_send_udp_peer_nonblock", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_CONTEXT_TCP] = call_t{"NtDeviceIoControlFile$afd_set_context_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_CONTEXT_UDP] = call_t{"NtDeviceIoControlFile$afd_set_context_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_TCP_ACCEPTED] = call_t{"NtDeviceIoControlFile$afd_set_information_nonblock_tcp_accepted", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_TCP_BOUND] = call_t{"NtDeviceIoControlFile$afd_set_information_nonblock_tcp_bound", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_TCP_CONNECTED] = call_t{"NtDeviceIoControlFile$afd_set_information_nonblock_tcp_connected", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_TCP_CREATED] = call_t{"NtDeviceIoControlFile$afd_set_information_nonblock_tcp_created", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_TCP_LISTENING] = call_t{"NtDeviceIoControlFile$afd_set_information_nonblock_tcp_listening", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_UDP_BOUND] = call_t{"NtDeviceIoControlFile$afd_set_information_nonblock_udp_bound", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_UDP_CREATED] = call_t{"NtDeviceIoControlFile$afd_set_information_nonblock_udp_created", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_INFORMATION_NONBLOCK_UDP_PEERED] = call_t{"NtDeviceIoControlFile$afd_set_information_nonblock_udp_peered", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_CONNECT_DATA_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_set_receive_connect_data_length_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_CONNECT_DATA_LENGTH_UDP] = call_t{"NtDeviceIoControlFile$afd_set_receive_connect_data_length_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_CONNECT_OPTIONS_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_set_receive_connect_options_length_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_CONNECT_OPTIONS_LENGTH_UDP] = call_t{"NtDeviceIoControlFile$afd_set_receive_connect_options_length_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_DISCONNECT_DATA_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_set_receive_disconnect_data_length_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_DISCONNECT_DATA_LENGTH_UDP] = call_t{"NtDeviceIoControlFile$afd_set_receive_disconnect_data_length_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_DISCONNECT_OPTIONS_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_set_receive_disconnect_options_length_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RECEIVE_DISCONNECT_OPTIONS_LENGTH_UDP] = call_t{"NtDeviceIoControlFile$afd_set_receive_disconnect_options_length_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RETURNED_RECEIVE_CONNECT_DATA_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_set_returned_receive_connect_data_length_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RETURNED_RECEIVE_CONNECT_OPTIONS_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_set_returned_receive_connect_options_length_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RETURNED_RECEIVE_DISCONNECT_DATA_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_set_returned_receive_disconnect_data_length_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_RETURNED_RECEIVE_DISCONNECT_OPTIONS_LENGTH_TCP] = call_t{"NtDeviceIoControlFile$afd_set_returned_receive_disconnect_options_length_tcp", 0, {}, (syscall_t)NtDeviceIoControlFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_CONNECT_DATA_TCP] = call_t{"NtDeviceIoControlFile$afd_set_send_connect_data_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_CONNECT_DATA_UDP] = call_t{"NtDeviceIoControlFile$afd_set_send_connect_data_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_CONNECT_OPTIONS_TCP] = call_t{"NtDeviceIoControlFile$afd_set_send_connect_options_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_CONNECT_OPTIONS_UDP] = call_t{"NtDeviceIoControlFile$afd_set_send_connect_options_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_DISCONNECT_DATA_TCP] = call_t{"NtDeviceIoControlFile$afd_set_send_disconnect_data_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_DISCONNECT_DATA_UDP] = call_t{"NtDeviceIoControlFile$afd_set_send_disconnect_data_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_DISCONNECT_OPTIONS_TCP] = call_t{"NtDeviceIoControlFile$afd_set_send_disconnect_options_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_SEND_DISCONNECT_OPTIONS_UDP] = call_t{"NtDeviceIoControlFile$afd_set_send_disconnect_options_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_START_LISTEN_TCP] = call_t{"NtDeviceIoControlFile$afd_start_listen_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_START_LISTEN_TCP_DELAYED] = call_t{"NtDeviceIoControlFile$afd_start_listen_tcp_delayed", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_START_LISTEN_TCP_DELAYED_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_start_listen_tcp_delayed_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_START_LISTEN_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_start_listen_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SUPER_ACCEPT_TCP] = call_t{"NtDeviceIoControlFile$afd_super_accept_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_input_handle8_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SUPER_ACCEPT_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_super_accept_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_input_handle8_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_file_accept_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_file_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_accept_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_UNBIND_TCP] = call_t{"NtDeviceIoControlFile$afd_unbind_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_UNBIND_UDP] = call_t{"NtDeviceIoControlFile$afd_unbind_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_UNCONNECT_UDP] = call_t{"NtDeviceIoControlFile$afd_unconnect_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_DELAYED_TCP] = call_t{"NtDeviceIoControlFile$afd_wait_for_listen_delayed_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_DELAYED_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_wait_for_listen_delayed_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_LIFO_PENDING_TCP] = call_t{"NtDeviceIoControlFile$afd_wait_for_listen_lifo_pending_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_LIFO_PENDING_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_wait_for_listen_lifo_pending_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_LIFO_TCP] = call_t{"NtDeviceIoControlFile$afd_wait_for_listen_lifo_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_LIFO_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_wait_for_listen_lifo_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_PENDING_TCP] = call_t{"NtDeviceIoControlFile$afd_wait_for_listen_pending_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_PENDING_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_wait_for_listen_pending_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_TCP] = call_t{"NtDeviceIoControlFile$afd_wait_for_listen_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_WAIT_FOR_LISTEN_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_wait_for_listen_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_CANCELIO_AFD_ADDRESS_LIST_CHANGE_PENDING] = call_t{"CancelIo$afd_address_list_change_pending", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIO_AFD_ADDRESS_LIST_CHANGE_PENDING_NONBLOCK] = call_t{"CancelIo$afd_address_list_change_pending_nonblock", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIO_AFD_LISTEN_IRP_PENDING] = call_t{"CancelIo$afd_listen_irp_pending", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIO_AFD_LISTEN_IRP_PENDING_LIFO] = call_t{"CancelIo$afd_listen_irp_pending_lifo", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIO_AFD_LISTEN_IRP_PENDING_LIFO_NONBLOCK] = call_t{"CancelIo$afd_listen_irp_pending_lifo_nonblock", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIO_AFD_LISTEN_IRP_PENDING_NONBLOCK] = call_t{"CancelIo$afd_listen_irp_pending_nonblock", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIO_AFD_ROUTING_INTERFACE_CHANGE_PENDING] = call_t{"CancelIo$afd_routing_interface_change_pending", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIO_AFD_ROUTING_INTERFACE_CHANGE_PENDING_NONBLOCK] = call_t{"CancelIo$afd_routing_interface_change_pending_nonblock", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIO_AFD_UDP_PEER_SEND_MESSAGE_PENDING] = call_t{"CancelIo$afd_udp_peer_send_message_pending", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIO_AFD_UDP_SEND_DATAGRAM_PENDING] = call_t{"CancelIo$afd_udp_send_datagram_pending", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIO_AFD_UDP_SEND_MESSAGE_PENDING] = call_t{"CancelIo$afd_udp_send_message_pending", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIO_AFD_UDP_SEND_PENDING] = call_t{"CancelIo$afd_udp_send_pending", 0, {}, (syscall_t)windows_cancel_io};
	syscalls[W32_CANCELIOEX_AFD_ACCEPT_SUPER_DISCONNECT_PENDING] = call_t{"CancelIoEx$afd_accept_super_disconnect_pending", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_ACCEPT_SUPER_DISCONNECT_PENDING_NONBLOCK] = call_t{"CancelIoEx$afd_accept_super_disconnect_pending_nonblock", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_ADDRESS_LIST_CHANGE_PENDING] = call_t{"CancelIoEx$afd_address_list_change_pending", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_ADDRESS_LIST_CHANGE_PENDING_NONBLOCK] = call_t{"CancelIoEx$afd_address_list_change_pending_nonblock", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_LISTEN_IRP_PENDING] = call_t{"CancelIoEx$afd_listen_irp_pending", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_LISTEN_IRP_PENDING_LIFO] = call_t{"CancelIoEx$afd_listen_irp_pending_lifo", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_LISTEN_IRP_PENDING_LIFO_NONBLOCK] = call_t{"CancelIoEx$afd_listen_irp_pending_lifo_nonblock", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_LISTEN_IRP_PENDING_NONBLOCK] = call_t{"CancelIoEx$afd_listen_irp_pending_nonblock", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_ROUTING_INTERFACE_CHANGE_PENDING] = call_t{"CancelIoEx$afd_routing_interface_change_pending", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_ROUTING_INTERFACE_CHANGE_PENDING_NONBLOCK] = call_t{"CancelIoEx$afd_routing_interface_change_pending_nonblock", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_SAN_CONTEXT] = call_t{"CancelIoEx$afd_san_context", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_SUPER_DISCONNECT_PENDING] = call_t{"CancelIoEx$afd_super_disconnect_pending", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_SUPER_DISCONNECT_PENDING_NONBLOCK] = call_t{"CancelIoEx$afd_super_disconnect_pending_nonblock", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_UDP_PEER_SEND_MESSAGE_PENDING] = call_t{"CancelIoEx$afd_udp_peer_send_message_pending", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_UDP_SEND_DATAGRAM_PENDING] = call_t{"CancelIoEx$afd_udp_send_datagram_pending", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_UDP_SEND_MESSAGE_PENDING] = call_t{"CancelIoEx$afd_udp_send_message_pending", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CANCELIOEX_AFD_UDP_SEND_PENDING] = call_t{"CancelIoEx$afd_udp_send_pending", 0, {}, (syscall_t)windows_cancel_io_ex};
	syscalls[W32_CLOSEHANDLE_AFD_ACCEPT_SUPER_DISCONNECT_PENDING] = call_t{"CloseHandle$afd_accept_super_disconnect_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_ACCEPT_SUPER_DISCONNECT_PENDING_NONBLOCK] = call_t{"CloseHandle$afd_accept_super_disconnect_pending_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_ACCEPT_TRANSMIT_CLOSING] = call_t{"CloseHandle$afd_accept_transmit_closing", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_ACCEPT_TRANSMIT_CLOSING_NONBLOCK] = call_t{"CloseHandle$afd_accept_transmit_closing_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_ACCEPT_TRANSMIT_PENDING] = call_t{"CloseHandle$afd_accept_transmit_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_ACCEPT_TRANSMIT_PENDING_NONBLOCK] = call_t{"CloseHandle$afd_accept_transmit_pending_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_ADDRESS_LIST_CHANGE_PENDING] = call_t{"CloseHandle$afd_address_list_change_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_ADDRESS_LIST_CHANGE_PENDING_NONBLOCK] = call_t{"CloseHandle$afd_address_list_change_pending_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_LISTEN_IRP_PENDING] = call_t{"CloseHandle$afd_listen_irp_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_LISTEN_IRP_PENDING_LIFO] = call_t{"CloseHandle$afd_listen_irp_pending_lifo", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_LISTEN_IRP_PENDING_LIFO_NONBLOCK] = call_t{"CloseHandle$afd_listen_irp_pending_lifo_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_LISTEN_IRP_PENDING_NONBLOCK] = call_t{"CloseHandle$afd_listen_irp_pending_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_ROUTING_INTERFACE_CHANGE_PENDING] = call_t{"CloseHandle$afd_routing_interface_change_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_ROUTING_INTERFACE_CHANGE_PENDING_NONBLOCK] = call_t{"CloseHandle$afd_routing_interface_change_pending_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_SAN_CONTEXT] = call_t{"CloseHandle$afd_san_context", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_SUPER_DISCONNECT_PENDING] = call_t{"CloseHandle$afd_super_disconnect_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_SUPER_DISCONNECT_PENDING_NONBLOCK] = call_t{"CloseHandle$afd_super_disconnect_pending_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_SEND_CONNECT_DATA] = call_t{"CloseHandle$afd_tcp_send_connect_data", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_SEND_CONNECT_OPTIONS] = call_t{"CloseHandle$afd_tcp_send_connect_options", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_SEND_DISCONNECT_DATA] = call_t{"CloseHandle$afd_tcp_send_disconnect_data", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_SEND_DISCONNECT_OPTIONS] = call_t{"CloseHandle$afd_tcp_send_disconnect_options", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_TRANSMIT_CLOSING] = call_t{"CloseHandle$afd_tcp_transmit_closing", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_TRANSMIT_CLOSING_NONBLOCK] = call_t{"CloseHandle$afd_tcp_transmit_closing_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_TRANSMIT_PENDING] = call_t{"CloseHandle$afd_tcp_transmit_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_TRANSMIT_PENDING_NONBLOCK] = call_t{"CloseHandle$afd_tcp_transmit_pending_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_PEER_SEND_MESSAGE_PENDING] = call_t{"CloseHandle$afd_udp_peer_send_message_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_SEND_CONNECT_DATA] = call_t{"CloseHandle$afd_udp_send_connect_data", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_SEND_CONNECT_OPTIONS] = call_t{"CloseHandle$afd_udp_send_connect_options", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_SEND_DATAGRAM_PENDING] = call_t{"CloseHandle$afd_udp_send_datagram_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_SEND_DISCONNECT_DATA] = call_t{"CloseHandle$afd_udp_send_disconnect_data", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_SEND_DISCONNECT_OPTIONS] = call_t{"CloseHandle$afd_udp_send_disconnect_options", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_SEND_MESSAGE_PENDING] = call_t{"CloseHandle$afd_udp_send_message_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_SEND_PENDING] = call_t{"CloseHandle$afd_udp_send_pending", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_NTCREATEFILE_AFD_SAN_HELPER] = call_t{"NtCreateFile$afd_san_helper", 0, {}, (syscall_t)NtCreateFile};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_ADDRESS_LIST_CHANGE_UDP] = call_t{"NtDeviceIoControlFile$afd_address_list_change_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECTEX_TCP] = call_t{"NtDeviceIoControlFile$afd_connectex_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECTEX_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_connectex_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECTEX_UDP] = call_t{"NtDeviceIoControlFile$afd_connectex_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_CONNECTEX_UDP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_connectex_udp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_TCP_SET] = call_t{"NtDeviceIoControlFile$afd_get_qos_tcp_set", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_TLI] = call_t{"NtDeviceIoControlFile$afd_get_qos_tli", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_GET_QOS_UDP_SET] = call_t{"NtDeviceIoControlFile$afd_get_qos_udp_set", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_NOTIFY_SOCK_DRAIN] = call_t{"NtDeviceIoControlFile$afd_notify_sock_drain", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_NOTIFY_SOCK_REGISTER] = call_t{"NtDeviceIoControlFile$afd_notify_sock_register", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_MESSAGE_UDP_BOUND_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_receive_message_udp_bound_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_RECEIVE_MESSAGE_UDP_PEER_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_receive_message_udp_peer_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_ROUTING_INTERFACE_CHANGE_UDP] = call_t{"NtDeviceIoControlFile$afd_routing_interface_change_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_ACQUIRE_CONTEXT] = call_t{"NtDeviceIoControlFile$afd_san_acquire_context", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_ADDR_LIST_CHANGE] = call_t{"NtDeviceIoControlFile$afd_san_addr_list_change", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_CONNECT_HANDLER] = call_t{"NtDeviceIoControlFile$afd_san_connect_handler", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_CEMENT_ENDPOINT] = call_t{"NtDeviceIoControlFile$afd_san_fast_cement_endpoint", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_COMPLETE_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_san_fast_complete_accept", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_COMPLETE_IO] = call_t{"NtDeviceIoControlFile$afd_san_fast_complete_io", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_COMPLETE_REQUEST] = call_t{"NtDeviceIoControlFile$afd_san_fast_complete_request", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_GET_PHYSICAL_ADDR] = call_t{"NtDeviceIoControlFile$afd_san_fast_get_physical_addr", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_GET_SERVICE_PID] = call_t{"NtDeviceIoControlFile$afd_san_fast_get_service_pid", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_PROVIDER_CHANGE] = call_t{"NtDeviceIoControlFile$afd_san_fast_provider_change", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_REFRESH_ENDPOINT] = call_t{"NtDeviceIoControlFile$afd_san_fast_refresh_endpoint", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_RESET_EVENTS] = call_t{"NtDeviceIoControlFile$afd_san_fast_reset_events", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_SET_EVENTS] = call_t{"NtDeviceIoControlFile$afd_san_fast_set_events", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_SET_SERVICE_PROCESS] = call_t{"NtDeviceIoControlFile$afd_san_fast_set_service_process", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SAN_FAST_TRANSFER_CTX] = call_t{"NtDeviceIoControlFile$afd_san_fast_transfer_ctx", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_send_message_accept", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_send_message_accept_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_TCP] = call_t{"NtDeviceIoControlFile$afd_send_message_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_send_message_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_UDP_BOUND] = call_t{"NtDeviceIoControlFile$afd_send_message_udp_bound", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_UDP_BOUND_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_send_message_udp_bound_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_UDP_PEER] = call_t{"NtDeviceIoControlFile$afd_send_message_udp_peer", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SEND_MESSAGE_UDP_PEER_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_send_message_udp_peer_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_QOS_TCP] = call_t{"NtDeviceIoControlFile$afd_set_qos_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_QOS_TLI] = call_t{"NtDeviceIoControlFile$afd_set_qos_tli", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SET_QOS_UDP] = call_t{"NtDeviceIoControlFile$afd_set_qos_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SOCKET_TRANSFER_BEGIN] = call_t{"NtDeviceIoControlFile$afd_socket_transfer_begin", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SOCKET_TRANSFER_END] = call_t{"NtDeviceIoControlFile$afd_socket_transfer_end", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SQM] = call_t{"NtDeviceIoControlFile$afd_sqm", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SUPER_CONNECT_TCP] = call_t{"NtDeviceIoControlFile$afd_super_connect_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SUPER_CONNECT_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_super_connect_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SUPER_CONNECT_TLI] = call_t{"NtDeviceIoControlFile$afd_super_connect_tli", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SUPER_DISCONNECT_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_super_disconnect_accept", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SUPER_DISCONNECT_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_super_disconnect_accept_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SUPER_DISCONNECT_TCP] = call_t{"NtDeviceIoControlFile$afd_super_disconnect_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_SUPER_DISCONNECT_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_super_disconnect_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_transmit_file_accept", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_BUFFERS_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_file_buffers_accept_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_BUFFERS_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_file_buffers_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_DISCONNECT_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_transmit_file_disconnect_accept", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_DISCONNECT_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_file_disconnect_accept_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_DISCONNECT_TCP] = call_t{"NtDeviceIoControlFile$afd_transmit_file_disconnect_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_DISCONNECT_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_file_disconnect_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_REUSE_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_transmit_file_reuse_accept", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_REUSE_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_file_reuse_accept_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_REUSE_TCP] = call_t{"NtDeviceIoControlFile$afd_transmit_file_reuse_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_REUSE_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_file_reuse_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_FILE_TCP] = call_t{"NtDeviceIoControlFile$afd_transmit_file_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_accept", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_DISCONNECT_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_disconnect_accept", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_DISCONNECT_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_disconnect_accept_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_DISCONNECT_TCP] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_disconnect_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_DISCONNECT_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_disconnect_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_FILE_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_file_accept_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_FILE_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_file_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_REUSE_ACCEPT] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_reuse_accept", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_REUSE_ACCEPT_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_reuse_accept_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_REUSE_TCP] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_reuse_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_REUSE_TCP_NONBLOCK] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_reuse_tcp_nonblock", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_TRANSMIT_PACKETS_TCP] = call_t{"NtDeviceIoControlFile$afd_transmit_packets_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_VALIDATE_GROUP_RECHECK_TCP] = call_t{"NtDeviceIoControlFile$afd_validate_group_recheck_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_VALIDATE_GROUP_RECHECK_UDP] = call_t{"NtDeviceIoControlFile$afd_validate_group_recheck_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_VALIDATE_GROUP_TCP] = call_t{"NtDeviceIoControlFile$afd_validate_group_tcp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_NTDEVICEIOCTLFILE_AFD_VALIDATE_GROUP_UDP] = call_t{"NtDeviceIoControlFile$afd_validate_group_udp", 0, {}, (syscall_t)windows_nt_device_io_control_file_state};
	syscalls[W32_CLOSEHANDLE_AFD_RIO_ENDPOINT] = call_t{"CloseHandle$afd_rio_endpoint", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_RIO_REGISTRATION_DOMAIN] = call_t{"CloseHandle$afd_rio_registration_domain", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_RIO_RQPAIR] = call_t{"CloseHandle$afd_rio_rqpair", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_SAN_ENDPOINT] = call_t{"CloseHandle$afd_san_endpoint", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_SAN_HELPER] = call_t{"CloseHandle$afd_san_helper", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_ACCEPTED] = call_t{"CloseHandle$afd_tcp_accepted", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_ACCEPTED_NONBLOCK] = call_t{"CloseHandle$afd_tcp_accepted_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_BOUND] = call_t{"CloseHandle$afd_tcp_bound", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_BOUND_NONBLOCK] = call_t{"CloseHandle$afd_tcp_bound_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_CONNECTED] = call_t{"CloseHandle$afd_tcp_connected", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_CONNECTED_NONBLOCK] = call_t{"CloseHandle$afd_tcp_connected_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_CREATED] = call_t{"CloseHandle$afd_tcp_created", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_CREATED_NONBLOCK] = call_t{"CloseHandle$afd_tcp_created_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_DISCONNECTED] = call_t{"CloseHandle$afd_tcp_disconnected", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_LISTEN_BACKLOG] = call_t{"CloseHandle$afd_tcp_listen_backlog", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_LISTEN_BACKLOG_NONBLOCK] = call_t{"CloseHandle$afd_tcp_listen_backlog_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_LISTENING] = call_t{"CloseHandle$afd_tcp_listening", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_LISTENING_DELAYED] = call_t{"CloseHandle$afd_tcp_listening_delayed", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_LISTENING_DELAYED_NONBLOCK] = call_t{"CloseHandle$afd_tcp_listening_delayed_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TCP_LISTENING_NONBLOCK] = call_t{"CloseHandle$afd_tcp_listening_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_TLI_ENDPOINT] = call_t{"CloseHandle$afd_tli_endpoint", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_BOUND] = call_t{"CloseHandle$afd_udp_bound", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_BOUND_NONBLOCK] = call_t{"CloseHandle$afd_udp_bound_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_CREATED] = call_t{"CloseHandle$afd_udp_created", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_CREATED_NONBLOCK] = call_t{"CloseHandle$afd_udp_created_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_PEERED] = call_t{"CloseHandle$afd_udp_peered", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_PEERED_EXTERNAL] = call_t{"CloseHandle$afd_udp_peered_external", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_PEERED_EXTERNAL_NONBLOCK] = call_t{"CloseHandle$afd_udp_peered_external_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_CLOSEHANDLE_AFD_UDP_PEERED_NONBLOCK] = call_t{"CloseHandle$afd_udp_peered_nonblock", 0, {}, (syscall_t)CloseHandle};
	syscalls[W32_NTREADFILE_AFD_ACCEPT_NONBLOCK] = call_t{"NtReadFile$afd_accept_nonblock", 0, {}, (syscall_t)NtReadFile};
	syscalls[W32_NTREADFILE_AFD_TCP_NONBLOCK] = call_t{"NtReadFile$afd_tcp_nonblock", 0, {}, (syscall_t)NtReadFile};
	syscalls[W32_NTREADFILE_AFD_UDP_PEER_NONBLOCK] = call_t{"NtReadFile$afd_udp_peer_nonblock", 0, {}, (syscall_t)NtReadFile};
	syscalls[W32_NTWRITEFILE_AFD_ACCEPT] = call_t{"NtWriteFile$afd_accept", 0, {}, (syscall_t)NtWriteFile};
	syscalls[W32_NTWRITEFILE_AFD_ACCEPT_NONBLOCK] = call_t{"NtWriteFile$afd_accept_nonblock", 0, {}, (syscall_t)NtWriteFile};
	syscalls[W32_NTWRITEFILE_AFD_TCP] = call_t{"NtWriteFile$afd_tcp", 0, {}, (syscall_t)NtWriteFile};
	syscalls[W32_NTWRITEFILE_AFD_TCP_NONBLOCK] = call_t{"NtWriteFile$afd_tcp_nonblock", 0, {}, (syscall_t)NtWriteFile};
	syscalls[W32_NTWRITEFILE_AFD_UDP_PEER] = call_t{"NtWriteFile$afd_udp_peer", 0, {}, (syscall_t)NtWriteFile};
	syscalls[W32_NTWRITEFILE_AFD_UDP_PEER_NONBLOCK] = call_t{"NtWriteFile$afd_udp_peer_nonblock", 0, {}, (syscall_t)NtWriteFile};
	syscalls[W32_GETKERNELOBJECTSECURITY_AFD_ENDPOINT] = call_t{"GetKernelObjectSecurity$afd_endpoint", 0, {}, (syscall_t)GetKernelObjectSecurity};
	syscalls[W32_SETKERNELOBJECTSECURITY_AFD_ENDPOINT] = call_t{"SetKernelObjectSecurity$afd_endpoint", 0, {}, (syscall_t)SetKernelObjectSecurity};
	syscalls[W32_NTFSCONTROLFILE] = call_t{"NtFsControlFile", 0, {}, (syscall_t)NtFsControlFile};
	syscalls[W32_NTFSCONTROLFILE_NTFS_GET_COMP] = call_t{"NtFsControlFile$ntfs_get_compression", 0, {}, (syscall_t)NtFsControlFile};
	syscalls[W32_NTFSCONTROLFILE_NTFS_QUERY_ALLOC_RANGES] = call_t{"NtFsControlFile$ntfs_query_allocated_ranges", 0, {}, (syscall_t)NtFsControlFile};
	syscalls[W32_NTFSCONTROLFILE_NTFS_SET_COMP] = call_t{"NtFsControlFile$ntfs_set_compression", 0, {}, (syscall_t)NtFsControlFile};
	syscalls[W32_NTFSCONTROLFILE_NTFS_SET_SPARSE] = call_t{"NtFsControlFile$ntfs_set_sparse", 0, {}, (syscall_t)NtFsControlFile};
	syscalls[W32_NTFSCONTROLFILE_NTFS_SET_ZERO_DATA] = call_t{"NtFsControlFile$ntfs_set_zero_data", 0, {}, (syscall_t)NtFsControlFile};
	syscalls[W32_NTREADFILE] = call_t{"NtReadFile", 0, {}, (syscall_t)NtReadFile};
	syscalls[W32_NTSETINFOFILE_BASIC] = call_t{"NtSetInformationFile$basic", 0, {}, (syscall_t)NtSetInformationFile};
	syscalls[W32_NTWRITEFILE] = call_t{"NtWriteFile", 0, {}, (syscall_t)NtWriteFile};
#define INIT_NYX_SERVICE_ENTRY(kind, target_id, target_name, service_name, service_number) \
	init_nyx_##kind##_service(target_id, target_name, service_name, service_number);
	WINDOWS_NYX_SERVICE_TABLE_26200(INIT_NYX_SERVICE_ENTRY)
#undef INIT_NYX_SERVICE_ENTRY
}
